### ISSUE TITLE
Solution File is Invalid

### ISSUE THREAD

**Issue by chshridhar** [OfficeDev/microsoft-teams-apps-incentives#11]
After the first step of creating SharePoint list ,uploading the Powerapps Solution is providing the following error any help is appreciated.

![Solution File is Invalid](https://user-images.githubusercontent.com/66700349/84200771-daaa3880-aa6c-11ea-9a23-d4c798226af2.png)

**Comment by Srivatsan0102** [comment]
How did you create the sharepoint lists, was it through the powershell script or manually? And in what step are you getting this error, during creating the lists or when importing the powerapp? Some more context is required to understand the issue.

**Comment by chshridhar** [comment]
dsfdsf

**Comment by chshridhar** [comment]
Lists has been created manually,The error popped up when importing the package for powerapps

**Comment by chshridhar** [comment]
Imported as Canvas app worked thanks
