### ISSUE TITLE
Activities not Showing in Home Screen (but are added and active in Admin panel)

### ISSUE THREAD

**Issue by CaivanNisha** [OfficeDev/microsoft-teams-apps-incentives#12]
Hi there,

Love this app. I've added some sample activities with points, ensured they are active and end past today's date. However, they still aren't showing up in the Home screen. I've looked through the app itself in powerapps studio and it appears to be pulling the correct list from Sharepoint. I've confirmed the list is created and the activities are there. (the sharepoint lists and site were created with the powershell script)
![image](https://user-images.githubusercontent.com/47901400/85631889-4f23d080-b644-11ea-9605-1f8ba717afee.png)

![image](https://user-images.githubusercontent.com/47901400/85631934-6498fa80-b644-11ea-8b7c-8717fa23c66f.png)

![image](https://user-images.githubusercontent.com/47901400/85632023-8a260400-b644-11ea-9fc7-209290170cd5.png)

**Comment by Srivatsan0102** [comment]
Hi,
Our dev team is looking into this issue, there may have been some updates in the Power app platform due to which the activities are not being loaded properly. We'll let you know once we find a resolution for this.

**Comment by CaivanNisha** [comment]
Hi there,
I found a resolution. The formula for Gallery3 uses "IsIncentiveLive=true"; I had to change this to "IsIncentiveLive<>False". It is a bit weird, I'm not sure why it's only recognizing "not false" instead of "true", but it is working now.
