### ISSUE TITLE
Leaderboard not updating

### ISSUE THREAD

**Issue by daburo** [OfficeDev/microsoft-teams-apps-incentives#13]
Hi there, we were using the app for a couple of weeks and it works perfect, suddenly today the leaderboard is not updating, but the sharepoint list it's showing correctly. Any solution? Thanks

![Leaderboard](https://user-images.githubusercontent.com/10717289/85646610-1c88d080-b662-11ea-8d96-e7a4752b6a78.png)
![sp list](https://user-images.githubusercontent.com/10717289/85646619-1f83c100-b662-11ea-90aa-2d7bb38466d1.jpeg)

**Comment by Srivatsan0102** [comment]
Hi,
Are you still facing the same issue? Sometimes it may take the powerapp some time to update the leaderboard, and if the sharepoint lists are containing the data, then there shouldn't be any issues. How did you create the sharepoint lists, using the powershell script or by creating them manually?

**Comment by AdelphiTN** [comment]
Do you have more than 500 items in the userincentives list? If so, you need to increase the data set in the app.

**Comment by Ixinho** [comment]
> Do you have more than 500 items in the userincentives list? If so, you need to increase the data set in the app.

How exactly do you increase it? I am planning to use this in my environment and we will have more than 500 entries for sure, so i could that use that hint :)

**Comment by ukdeepak33** [comment]
i had same issue leaderboard was not updating after 500 items, when i increase limit to 2000, app was not performing well enough. is there any solution where we can increase limit over 3000 and app performs well.

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #43 . Closing this issue.
