### ISSUE TITLE
Column Name-Name

### ISSUE THREAD

**Issue by chshridhar** [OfficeDev/microsoft-teams-apps-incentives#14]
Name is reserved Column, How to add this Columns, One way could be we create column with 'IncenentiveName' and Rename it to Name.
<img width="369" alt="Name" src="https://user-images.githubusercontent.com/66700349/86022267-bc8e8300-b9ef-11ea-992f-b5315ad3ef42.png">

**Comment by lkanala** [comment]
Hi @chshridhar ,Please follow this link to create SharePoint column name  https://github.com/OfficeDev/microsoft-teams-apps-incentives/wiki/Troubleshooting#problems-related-to-sharepoint-list-creation
