### ISSUE TITLE
Incentives not appearing

### ISSUE THREAD

**Issue by Pher0ah** [OfficeDev/microsoft-teams-apps-incentives#16]
After deploying the app, and adding it into Teams, all is working except the "Activities with incentives" is always empty. Please can you advise what troubleshooting steps I can take to figure out why it is not showing; I have checked the backend list and it is populated with activities; and I can claim the code and the rewards; just the activities list is always empty in the user "Home" view.

![Screenshot](https://user-images.githubusercontent.com/46461320/87732550-a4509d80-c810-11ea-91e4-9256280fff5d.png)

**Comment by Pher0ah** [comment]
Hi, just found the issue; it seems that the logic statement in the filter is incorrect; instead of "true" I replaced this with "1" and it started working. Please update the zip package to reflect the same.

**Comment by lordneeko** [comment]
I can confirm this. SPO's "boolean" field is no longer an option, you only have a Yes/No option. When you use that, and use the API to get the data, you either get Yes or No, or you get 1 or 0.  You don't get true or false.  And apparently PowerApps isn't smart enough to associate 1 with true. /shrug

**Comment by sowmyavaradaraju** [comment]
So, what will be the exact solution for this , even i'm not able to find this incentives along with due dates on home screen , a little urgent , please do mention what will be the solution , tried changing the filter function from "true" to "1" , that didn't work as well. please do suggest

**Comment by gigmog** [comment]
> So, what will be the exact solution for this , even i'm not able to find this incentives along with due dates on home screen , a little urgent , please do mention what will be the solution , tried changing the filter function from "true" to "1" , that didn't work as well. please do suggest

To clarify what exactly needs to be changed, **Items** property for **Gallery3** within the **ActiveIncentivesGroup** has three instances of "IsIncentiveLive=true" that need to be changed to "IsIncentiveLive=1"

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #43 . Closing this issue.
