### ISSUE TITLE
Sort Order when there's a tie

### ISSUE THREAD

**Issue by AdelphiTN** [OfficeDev/microsoft-teams-apps-incentives#17]
I seem to get changing sort orders on refresh when there's a tie on points. How can I control that order? Preferably "ReceivedOn" descending or something like that to sort up the people who submitted sooner than others. Thanks!

**Comment by v-smahaj** [comment]
For Incentives app template repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
