### ISSUE TITLE
Checkbox2.DisplayMode has a Formula Error

### ISSUE THREAD

**Issue by lordneeko** [OfficeDev/microsoft-teams-apps-incentives#18]
![image](https://user-images.githubusercontent.com/11577533/89042909-b6086980-d315-11ea-8d70-03f2b804c40c.png)

I cannot figure out what the formula is supposed to be pointing at, but as you can see the "Points" object is not found.
Error says: 
![image](https://user-images.githubusercontent.com/11577533/89043002-dafcdc80-d315-11ea-88e6-f746b3e060c1.png)

I have not modified it from the template at all.

**Comment by taytay91** [comment]
Hey, I ended up changing "Points" to just the number 0. This seems to work fine, I also ran into a range of other small issues as well where the incentives wouldn't show and it was because the formula referencing "IsIncentiveActive" was using true or false and needed to use 1 or 0.

**Comment by anpai** [comment]
in the formula - update it as "ThisItem.Points"

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #43 . Closing this issue.
