### ISSUE TITLE
Only Display members of the sharepoint list

### ISSUE THREAD

**Issue by zkhan784** [OfficeDev/microsoft-teams-apps-incentives#20]
Hello,

Currently, I can see all the users of Office365 in the "Name of Team Member" drop down search column. Can I please restrict the search only to users who are part of my sharepoint list "Incentives" if possible. I would really appreciate the guidance here.

**Comment by v-smahaj** [comment]
For Incentives app template repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
