### ISSUE TITLE
Duplicate entries - Incentive Codes

### ISSUE THREAD

**Issue by zkhan784** [OfficeDev/microsoft-teams-apps-incentives#21]
Hello,

Currently, when I re-enter the Incentive which I have already used, it gives me an error saying "You already collected points for this code ". My Activities are repetitive and needs multiple entries of the same incentive code. Please help me change this setting.

**Comment by Ixinho** [comment]
> Hello,
> 
> Currently, when I re-enter the Incentive which I have already used, it gives me an error saying "You already collected points for this code ". My Activities are repetitive and needs multiple entries of the same incentive code. Please help me change this setting.

Did you find any way to get around this?

**Comment by v-smahaj** [comment]
For Incentives app template repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
