### ISSUE TITLE
Unable to create the SharePoint list using Powershell

### ISSUE THREAD

**Issue by kumari-r** [OfficeDev/microsoft-teams-apps-incentives#22]
Hello Team, 

I was trying to create the SharePoint lists via Powershell in order to deploy the Incentives app. I followed the instructions from the deployment guide but received the below error. 

Could you check what went wrong here and if we have to do anything extra apart from the deployment guide?
 
![error](https://user-images.githubusercontent.com/68238430/90149652-5d6bae80-dda2-11ea-8bee-d7a9ce54c129.jpg)

Please advise.

**Comment by v-smahaj** [comment]
We were not able to repro this issue.
Please let us know if issue is not resolved yet.
