### ISSUE TITLE
Error message post entering the Admin Teams groupId

### ISSUE THREAD

**Issue by kumari-r** [OfficeDev/microsoft-teams-apps-incentives#23]
In PowerApps, when I select the SharePoint lists, connect and enter the Admin Teams group Id, I see few error messages on the screen, what are those error messages? 
The app worked fine in Teams, but it appears for all the Incentive app deployments in PowerApps. The screenshot below for reference:

![image](https://user-images.githubusercontent.com/68238430/90155640-2fd63380-dda9-11ea-8f8e-e112eee86b28.png)

**Comment by v-smahaj** [comment]
Thank you for reporting this. We have implemented a fix and pushed it as part of pull request #43 . Closing this issue.
