### ISSUE TITLE
Automatic way of providing Incentive/Activity code to users if we have list of large users

### ISSUE THREAD

**Issue by kumari-r** [OfficeDev/microsoft-teams-apps-incentives#24]
My Team consists of more than 1000 users and we are trying to deploy this app for one of our Teams. Now, every time the users complete an activity, they have to ask the Admin for the code, and it not possible for the admin to keep sending an email with the code to each user. Its time taking and lots of manual work. 
We cannot inform the entire team about the activity code as they might collect the points without completing the activity. It's not possible to keep a track of everyones activity completion as its time-consuming. 

Is there any other way/automatic option for this?

**Comment by taytay91** [comment]
Try automating it a little using PowerAutomate/Flow?

**Comment by kumari-r** [comment]
@taytay91 Thank you but I do not know how to automate it as I have not used Power Automate/Flow for PowerApps much. Could you shed some light on that?

Many thanks, 
Rupam

**Comment by nzivkovic12** [comment]
> @taytay91 Thank you but I do not know how to automate it as I have not used Power Automate/Flow for PowerApps much. Could you shed some light on that?
> 
> Many thanks,
> Rupam

Looking for his exact thing. Hoping there is a workaround. I can't figure out the "Activities with incentives" portion, that seems to be what we are looking for.

**Comment by v-smahaj** [comment]
For Incentives app template repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
