### ISSUE TITLE
App will not recognize Group ID

### ISSUE THREAD

**Issue by TomSchinler** [OfficeDev/microsoft-teams-apps-incentives#25]
I have followed the depolyment guide to the letter, but when I try to add the App to teams and run it, I am given this error:

> Office365Groups.ListGroupMembers failed: { "error": { "code": "Request_BadRequest", "message": "Invalid object identifier 'Enter Incentives app admins group Id here'.", "innerError": { "date": "2020-08-21T17:53:38", "request-id": "e132a3da-1da1-4931-87f8-e4f9949c7677" } } }

I have replaced the group ID in the OnStart() as can be seen here:
![image](https://user-images.githubusercontent.com/7664494/90922723-112bfa00-e3b2-11ea-892c-3e35e639ce61.png)

But when I run the app, via the web or inside of Teams I am given this:

![image](https://user-images.githubusercontent.com/7664494/90922811-3882c700-e3b2-11ea-9fed-e32c505ec096.png)

Any assistance is appreciated.

**Comment by jobin-t** [comment]
Hi Tom, Please make sure to re publish the Power Apps app after you make the groupid entry. This solved my issue.

**Comment by Ixinho** [comment]
I had the same issue, and i realized i was using the same team ID in which i published the app. You need to create a separate Team for Admins and to use that ID.
