### ISSUE TITLE
Redeem not working - issue with function Patch has some invalid arguments Button20.OnSelect

### ISSUE THREAD

**Issue by GalKoll** [OfficeDev/microsoft-teams-apps-incentives#29]
The Redeem button is not doing anything.  Any ideas? 

Issue
The function 'Patch' has some invalid arguments.
Location ^3 Button20 .OnSelect

![2020-10-02_15-18-12](https://user-images.githubusercontent.com/72258142/94922272-9979e080-04c2-11eb-80ee-19a937dfdb37.png)

**Comment by v-smahaj** [comment]
We were not able to repro this issue at our end. Can you try a fresh deployment. Let us know if the issue still persists.
