### ISSUE TITLE
Error while reading manifest.json: "manifestVersion" is required

### ISSUE THREAD

**Issue by TaraMHammond** [OfficeDev/microsoft-teams-apps-incentives#3]
I had a couple of issues following through the directions.  I had to create the lists manually.  It wouldn't let me create a column named "Name" in the Incentives list, so I had to make it IncentiveName.  Also, RewardName in the rewards table.  Once I had it in the Preview, I didn't see anything that said just download.  It said export, which seems reasonable.  However when I tried to import the custom app into Teams, I got this error: Error while reading manifest.json: "manifestVersion" is required.  Did I miss a step?

I would love to get this moving in our environment.  Thanks!

**Comment by LalithKanala** [comment]
https://github.com/OfficeDev/microsoft-teams-apps-incentives/wiki/Troubleshooting#problems-related-to-sharepoint-list-creation
Check the above mentioned troubleshooting link for creating column “Name”. We should not change the columns names as they are connected to Power app. The export option is for power apps. To upload the package into Teams, select the application, you will see add to teams on the top bar, click on it and a download button will appear, click on it, you can upload this package in Microsoft Teams. 
Thanks

**Comment by Schaboo** [comment]
Hi,

I have followed the setup step by step but after creating come check-ins I don't see any in reports.

Thanks 
Tomasz

**Comment by kaanaytemir** [comment]
`Add to Teams > Download app` in Power Apps Studio. This should be in the documentation.
