### ISSUE TITLE
Incentive App Issue

### ISSUE THREAD

**Issue by smouzong** [OfficeDev/microsoft-teams-apps-incentives#30]
Hi
i have problem to view "Activities" in TEAMS.
When i set the IsIncentiveLive to YES in Sharepoint i cannot view the activity in the home screen.

in SharePoint the value of the is "YES/NO" since value "BOOLEAN" is not available in SharePoint Online
![IsIncentiveLive-Tutorial Value](https://user-images.githubusercontent.com/72984595/96272090-8c321b00-0fc5-11eb-9f63-1d7aa3093d4b.jpg)
![IsIncentiveLive](https://user-images.githubusercontent.com/72984595/96272101-8d634800-0fc5-11eb-85c2-8c39e4e032b0.jpg)

Stephan
smouzong@gmail.com

**Comment by Ixinho** [comment]
> Hi
> i have problem to view "Activities" in TEAMS.
> When i set the IsIncentiveLive to YES in Sharepoint i cannot view the activity in the home screen.
> 
> in SharePoint the value of the is "YES/NO" since value "BOOLEAN" is not available in SharePoint Online
> ![IsIncentiveLive-Tutorial Value](https://user-images.githubusercontent.com/72984595/96272090-8c321b00-0fc5-11eb-9f63-1d7aa3093d4b.jpg)
> ![IsIncentiveLive](https://user-images.githubusercontent.com/72984595/96272101-8d634800-0fc5-11eb-85c2-8c39e4e032b0.jpg)
> 
> Stephan
> [smouzong@gmail.com](mailto:smouzong@gmail.com)

Hi Stephan,

were you able to fix this somehow? I am having the same issue

Nikola

**Comment by v-smahaj** [comment]
Thank you for reporting this. We have implemented a fix and pushed it as part of pull request #43. Closing this issue.
