### ISSUE TITLE
Increase dataset from 500 to 2000/5000?

### ISSUE THREAD

**Issue by Ixinho** [OfficeDev/microsoft-teams-apps-incentives#32]
I saw someone here mentioned that when the list reaches 500 items data set needs to be increased from 500 to 2000. 
Where and how do i configure that?
Which lists will it impact, all 4 or a specific one?
Can i set it to 5000? We will have that many items in 6 months or so.

Thank you

**Comment by narismadz** [comment]
![image](https://user-images.githubusercontent.com/16915716/101507656-5ef06080-39a9-11eb-8ba2-185ef3b2e69b.png)

**Comment by v-smahaj** [comment]
Thank you for reporting this. We have implemented a fix and pushed it as part of pull request #43. Closing this issue.
