### ISSUE TITLE
App requires premium plan

### ISSUE THREAD

**Issue by tixgrr00** [OfficeDev/microsoft-teams-apps-incentives#33]
After uploading and connecting lists to the app I tried to test connections and when running app I receive the "This app uses features that come with a Power Apps premium plan."  I do not see any premium connections.  I do not see documentation that they are even used.

**Comment by v-smahaj** [comment]
We were not able to reproduce this issue at our end. Can you try a fresh deployment. Let us know if the issue still persists.
