### ISSUE TITLE
When lunching the app in MS Teams, it is giving a message saying this app uses features that come with a Power Apps Premium plan. Start the Trial to use these features

### ISSUE THREAD

**Issue by koyyalamudi** [OfficeDev/microsoft-teams-apps-incentives#34]
When lunching the app in MS Teams, it is giving a message saying this app uses features that come with a Power Apps Premium plan. Start the Trial to use these features.

What premium features does this app using, Call the connector are in Within the SharePoint Realm. I am having E3 licenses.

Thanks
Praveen

**Comment by v-smahaj** [comment]
We were not able to reproduce this issue at our end. Can you try a fresh deployment. Let us know if the issue still persists.
