### ISSUE TITLE
Can't get data to populate in app

### ISSUE THREAD

**Issue by jcode234** [OfficeDev/microsoft-teams-apps-incentives#35]
![image](https://user-images.githubusercontent.com/75924343/102004351-cd03a180-3d74-11eb-84f9-b36a9056bb7d.png)

Hi, Can i please get some help? I can't seem to load any of my the team members in the app. The leaderboard just shows blank.

**Comment by v-smahaj** [comment]
We are not able to repro this issue at our end. Can you try a fresh deployment. Let us know if issue still persists.
