### ISSUE TITLE
"Activities with Incentives" section not displaying the activities

### ISSUE THREAD

**Issue by parkashpant** [OfficeDev/microsoft-teams-apps-incentives#37]
Hi! I have tried installing the app twice as per the deployment guide. However, whenever I create the activity, it doesn't reflect in the "Activities with Incentives" section. I checked the SharePoint list "Incentives" and instead of populating the "CreatedOn" field and it's populating "UpdatedBy" and "UpdatedOn" for newly created activities. can you please help?

**Comment by ndocosta** [comment]
Hi @parkashpant I'm having the same problem.
I've changed the code for "Gallery3" inside "ActiveIncentivesGroup". We need to change the comparison of "IsIncentiveLive = true" to "IsIncentiveLive <> false".
![Incentives_Activities](https://user-images.githubusercontent.com/12910235/108997424-7a5d3480-7697-11eb-99b8-d9455bd04361.jpg)
After doing this change and republishing the Power App it is now showing the Activities correctly.
Hope this help!

**Comment by Zunade** [comment]
Thanks, @ndocosta followed your instructions and its working now:

**replace:**
If(sortbycreated,Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive=true),Created,Descending),If(sortbyduedate,Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive=true),DueDate,Descending),Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive=true),DueDate,Ascending)))
**with**:
If(sortbycreated,Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive<> false ),Created,Descending),If(sortbyduedate,Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive<> false ),DueDate,Descending),Sort(Filter(Incentives_1,DueDate>=Today()&&IsIncentiveLive<> false ),DueDate,Ascending)))

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #43. Closing this issue.
