### ISSUE TITLE
Getting Error message after deploying the app in MS Teams

### ISSUE THREAD

**Issue by Samarth5629** [OfficeDev/microsoft-teams-apps-incentives#38]
Office365Groups.ListGroupMembers failed: { "error": { "code": "Request_BadRequest", "message": "Invalid object identifier 'Enter Incentives app admins group Id here'.", "innerError": { "date": "2021-02-03T02:43:13", "request-id": "****-****-****-****-************", "client-request-id": "********-****-****-****-************" } } }

**Comment by anpai** [comment]
The app deployment needs to be done by Windows Admin, since they have the access to Office365. So, you would need to ask your company Admin, to help you in the deployment, since the Office365 authentication is needed.

**Comment by nathancap** [comment]
Has this been solved, I am receiving the same issue

**Comment by nathancap** [comment]
@Samarth5629 solved?

**Comment by v-smahaj** [comment]
We were not able to repro this issue.
Can you please validate if all steps mentioned in Step 4 are followed, especially step 4.8.
"On left menu > select Tree view > app > under formula bar at the top > 'OnStart' function. Replace the Enter your GroupId here with the Admin team group id created in Step 3."
Let us know if issues is not resolved.
