### ISSUE TITLE
Activities with incentives section empty

### ISSUE THREAD

**Issue by Zunade** [OfficeDev/microsoft-teams-apps-incentives#39]
Good day 

Home block "Activities with incentives" empty and does not list any activities.

snippets:
[https://zunadecdn.blob.core.windows.net/publicpictures/Activities%20with%20incentives%20empty.png](url)
https://zunadecdn.blob.core.windows.net/publicpictures/Activities%20with%20incentives%20empty2.png

any recommendations please where can fix this

regards,
Zunade

**Comment by CountBacula** [comment]
@Zunade could I ask what you did to resolve this? I'm seeing the same issue currently. Everything else is working well. The Incentives are listed on the Admin screen but not the User screen.
