### ISSUE TITLE
Unable to deploy the app as it contains multiple formula errors

### ISSUE THREAD

**Issue by olivlum** [OfficeDev/microsoft-teams-apps-incentives#41]
Hello,

Once I've imported the app package into PowerApps and connected my SharePoint site (which has been correctly created), I face multiple formula errors which are below.

How can I fix them?
Thank you

![Error1](https://user-images.githubusercontent.com/9051082/113278772-9bdabd00-92e2-11eb-9430-ecacbed2d861.jpg)
![Error2](https://user-images.githubusercontent.com/9051082/113278774-9c735380-92e2-11eb-932a-2156b644556f.jpg)

**Comment by goalguy10** [comment]
I am having the same exact issue. Any updates?

**Comment by olivlum** [comment]
I don't know why but some errors does not appear anymore (I'm still having the issue with the "Points" that is not recognized).
But I'm able to publish now

**Comment by v-smahaj** [comment]
Thanks for reporting this. We have implemented a fix and pushed it as part of pull request #43 .

**Comment by Mintyfresh2764** [comment]
I'm seeing the exact same thing today in 2022. I used the most recent zip file. Any suggestions?

**Comment by cartayuk** [comment]
I have the same issue. Any Suggestions

![image](https://user-images.githubusercontent.com/107178191/172894566-fccdc4f1-cb6c-4997-8bcb-6d9a478a2219.png)
