### ISSUE TITLE
Timezone issue when using IncentivesApp

### ISSUE THREAD

**Issue by bchamnarnkit** [OfficeDev/microsoft-teams-apps-incentives#44]
Hi, we are currently working with a customer in using the IncentivesApp for their entire HR org, but ran into the following issues where we have set an end date to the points as a particular day, but on the sharepoint list from their back end systems is showing another day - with a 14 hour delay.
<img width="219" alt="Capture-IncentivesApp" src="https://user-images.githubusercontent.com/84174370/118238088-42110980-b4c2-11eb-8488-2ce9b3fbde72.PNG">

has anyone ever experienced this issue and is able to resolve it?

**Comment by v-smahaj** [comment]
Thanks for reporting. Can you try changing SharePoint site timezone to your local timezone.
Let us know if issue still persists.
