### ISSUE TITLE
Activities and rewards renamed to random characters

### ISSUE THREAD

**Issue by ambarishrh** [OfficeDev/microsoft-teams-apps-incentives#7]
I created few rewards and activities and now displayed as shown below. 

![image](https://user-images.githubusercontent.com/635458/82550100-112c1c00-9b6f-11ea-842e-ef2a686f0bcc.png)

![image](https://user-images.githubusercontent.com/635458/82550121-1a1ced80-9b6f-11ea-8e5f-4a0f82a51b7c.png)

Also are there any ways to retrieve the voucher code, to be used later?

**Comment by Srivatsan0102** [comment]
The random characters is basically the value corresponding to the title column on your sharepoint list. If you have manually created the lists, then there may be have been an error in defining the columns on the Sharepoint list and so it may be pointing to the Title column by mistake. You can try the deployment again by deploying using the powershell list and see if you get the correct values. Or, if you want to create the lists manually, follow the troubleshooting guide on how to add column names: https://github.com/OfficeDev/microsoft-teams-apps-incentives/wiki/Troubleshooting#problems-related-to-sharepoint-list-creation
