### ISSUE TITLE
Teams Incentives App Template Issue

### ISSUE THREAD

**Issue by SmartCareTeam** [OfficeDev/microsoft-teams-apps-incentives#8]
I am unable add/edit or save items via the Admin Tool in the Teams Incentives App. Touch based with Microsoft for the issue: 120052624000940, they were unable to resolve the issue and suggested we contact GitHub.

**Comment by Srivatsan0102** [comment]
This could be an issue caused when creating the Sharepoint lists. If you have created them using the powershell script as mentioned in the deployment guide, you shouldn't be running into too many problems. If created manually, make sure you create new columns by selecting add new column -> More -> Entering the column name, type and description. This will create your Sharepoint columns and lists without any problems. More information on this is available in the troubleshooting guide: https://github.com/OfficeDev/microsoft-teams-apps-incentives/wiki/Troubleshooting
