### ISSUE TITLE
How do we enable multiple inputs on completed activity

### ISSUE THREAD

**Issue by ninatorjesen** [OfficeDev/microsoft-teams-apps-incentives#9]
I would like to give my users possibility to register an activity multiple times (ex. participated in morning videomeeting). How do i enable this?

**Comment by Srivatsan0102** [comment]
We do not have multiple inputs in the current version of Incentives, the workaround for this would be to add an activity for each event that is to be attended multiple times and then the user would be able to redeem the points for each activity.

**Comment by ninatorjesen** [comment]
Ok, thank you - to be sure, is there nowhere in the code we could rewrite?
